server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /docs

spring:
  application:
    name: springsecurity
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity?serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: springstudent
    password: springstudent
#  data:
#    redis:
#      host: redis-container
#      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect